version: '3'

tasks:
  deploy:
    vars:
      IMG: '{{ .IMG | default "henrywhitaker3/mysql-provisioner" }}'
      TAG: '{{ .TAG | default "latest" }}'
    cmds:
    - make docker-build IMG={{ .IMG }}:{{ .TAG }}
    - kind load docker-image {{ .IMG }}:{{ .TAG }}
    - make deploy IMG={{ .IMG }}:{{ .TAG }}

  undeploy:
    - make undeploy

  apply:
    cmds:
      - kubectl apply -f config/samples/mysql-provisioner_v1beta1_connection.yaml
      - kubectl apply -f config/samples/mysql-provisioner_v1beta1_database.yaml
      - kubectl apply -f config/samples/mysql-provisioner_v1beta1_user.yaml

  delete:
    cmds:
      - kubectl delete -f config/samples/mysql-provisioner_v1beta1_database.yaml
      - kubectl delete -f config/samples/mysql-provisioner_v1beta1_user.yaml
      - kubectl delete -f config/samples/mysql-provisioner_v1beta1_connection.yaml

  generate:chart:
    cmds:
      - make helm

  release:chart:
    cmds:
      - |
        sed -i 's/newTag: v[0-9]*\.[0-9]*\.[0-9]*/newTag: v{{ .VERSION }}/g' config/manager/kustomization.yaml
      - |
        sed -i 's/appVersion: "[0-9]*\.[0-9]*\.[0-9]*"/appVersion: "{{ .VERSION }}"/g' charts/mysql-provisioner/Chart.yaml
      - |
        sed -i 's/version: [0-9]*\.[0-9]*\.[0-9]*/version: {{ .VERSION }}/g' charts/mysql-provisioner/Chart.yaml
      - task: generate:chart
      - git add .
      - git commit -m "Run release task" --allow-empty
      - git push

  release:pkg:
    cmds:
      - git tag v{{ .VERSION }}
      - git push origin v{{ .VERSION }}

  release:
    cmds:
      - task: release:chart
      - sleep 90
      - task: release:pkg
