version: '3'

tasks:
  deploy:
    vars:
      IMG: '{{ .IMG | default "henrywhitaker3/mysql-provisioner" }}'
      TAG: '{{ .TAG | default "latest" }}'
    cmds:
    - make docker-build IMG={{ .IMG }}:{{ .TAG }}
    - kind load docker-image {{ .IMG }}:{{ .TAG }}
    - make deploy IMG={{ .IMG }}:{{ .TAG }}

  undeploy:
    - make undeploy

  apply:
    cmds:
      - ./bin/kustomize build config/samples/ | kubectl apply -f -

  delete:
    cmds:
      - kubectl delete -f config/samples/mysql-provisioner_v1beta1_database.yaml
      - ./bin/kustomize build config/samples/ | kubectl delete -f -

  generate:chart:
    cmds:
      - make helm
