apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - connections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - connections/finalizers
  verbs:
  - update
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - connections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - mysql-provisioner.henrywhitaker.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-provisioner
    app.kubernetes.io/part-of: mysql-provisioner
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'