apiVersion: henrywhitaker3.my.domain/v1beta1
kind: MysqlConnection
metadata:
  labels:
    app.kubernetes.io/name: mysqlconnection
    app.kubernetes.io/instance: mysqlconnection-sample
    app.kubernetes.io/part-of: mysql-provisioner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-provisioner
  name: mysqlconnection-sample
spec:
  # TODO(user): Add fields here
