apiVersion: mysql-provisioner.henrywhitaker.com/v1beta1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/instance: user-sample
    app.kubernetes.io/part-of: mysql-provisioner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-provisioner
  name: user-sample
  finalizers:
    - mysql-provisioner.henrywhitaker.com/propogate
spec:
  name: sample-user
  host: "%"
  connectionRef:
    name: connection-sample
    namespace: default
  passwordSecretRef:
    name: password-sample
    key: password
  grants:
    - privileges: ALL PRIVILEGES
      to: "bongos . *"
